Description: >
    This template is design to deploy EC2 instance in AWS enviornment.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: PROD
  VpcId:
    Description: VPC ID for resources
    Type: String
    Default: VpcID
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable RDP access to the instance
    Type: String
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Default: KeyName
  InstanceType:
    Description: App EC2 instance type
    Type: String
    Default: InstanceType
  SubnetID:
    Description: App EC2 instance type
    Type: String
    Default: SubnetID
  ImageID:
    Description: App EC2 instance type
    Type: String
    Default: ImageID
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      ImageId: !Ref ImageID
      SubnetId: !Ref SubnetID
      SecurityGroupIds:
        - sg-0c003493910921cb9
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
        -
          DeviceName: /dev/xvdf
          Ebs:
            VolumeSize: 5
      Tags:
        - Key: Product
          Value: test
        - Key: Type
          Value: AppServer
      UserData:
        'Fn::Base64': !Sub |
            <powershell>
            Import-Module AWSPowerShell
            C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeDisks.ps1
            </powershell>
